#!/bin/sh

# board defaults, do not change in running system. Change /env/config
# instead

global.hostname=cfa10036
global.linux.bootargs.base="console=ttyAMA0,115200"

# Setup the USB related settings
global linux.bootargs.otg.vid="g_cdc.idVendor=0x223b"
global linux.bootargs.otg.pid="g_cdc.idProduct=0x2734"
global linux.bootargs.otg.man="g_cdc.iManufacturer=Crystalfontz"
global linux.bootargs.otg.product="g_cdc.iProduct=CFA-10036"

# Disable the console blank
global linux.bootargs.consoleblank="consoleblank=0"
